# ── Stage 1: PHP vendor + Wayfinder types ────────────────────────────────
# Fresh CI checkouts lack resources/js/{actions,routes} (gitignored);
# they must be generated by artisan before the frontend build.
FROM serversideup/php:8.4-fpm-nginx AS vendor

WORKDIR /var/www/html

COPY --chown=www-data:www-data composer.json composer.lock ./
RUN composer install --no-dev --no-scripts --optimize-autoloader --no-interaction --no-progress

# Container runs as www-data — ownership must be set at COPY time.
COPY --chown=www-data:www-data . .

RUN composer dump-autoload --optimize \
    && php artisan wayfinder:generate --with-form

# ── Stage 2: Frontend assets ─────────────────────────────────────────────
FROM node:20-alpine AS assets

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --no-audit --no-fund

# Pre-warmed laravel-vite-plugin font cache (committed to git) — keeps builds
# hermetic: no network fetch of fonts.bunny.net at build time.
COPY node_modules/.cache/laravel-vite-plugin ./node_modules/.cache/laravel-vite-plugin

COPY . .
COPY --from=vendor /var/www/html/resources/js/actions resources/js/actions
COPY --from=vendor /var/www/html/resources/js/routes resources/js/routes
COPY --from=vendor /var/www/html/resources/js/wayfinder resources/js/wayfinder

ENV VITE_WAYFINDER_COMMAND=true
RUN npm run build

# ── Stage 3: Production runtime ──────────────────────────────────────────
FROM serversideup/php:8.4-fpm-nginx

WORKDIR /var/www/html

COPY --chown=www-data:www-data . .

# Host-built manifests may reference dev-only providers — force a clean rebuild.
RUN rm -f bootstrap/cache/packages.php bootstrap/cache/services.php

COPY --from=vendor --chown=www-data:www-data /var/www/html/vendor ./vendor
COPY --from=assets --chown=www-data:www-data /app/public/build ./public/build
